# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d228243730984980e4604a0fec69e7aee48ac24cdb6765c52f15153bd24864c798c251e7e7027afa04756cc4f700e10077f3e21b23072bf5fa03b524425b8b5

test:
  secret_key_base: c5a1e3071fc4574003613a1accf39b4833e4b04f12a740c1dae072b447cb28f0a2969b60e71ca53dee005fd320537f61becf1b8dcd744ab3d6eba7d4ed32694e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
